"""add logo_filename to company_settings

Revision ID: 129833dcfbf1
Revises: 87574ceae7f2
Create Date: 2026-07-20 20:41:31.189042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129833dcfbf1'
down_revision: Union[str, Sequence[str], None] = '87574ceae7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('logo_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'logo_filename')
    # ### end Alembic commands ###
