"""remove vat_rate from products

Revision ID: 7d1b1420b942
Revises: 129833dcfbf1
Create Date: 2026-07-20 20:54:10.121232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1b1420b942'
down_revision: Union[str, Sequence[str], None] = '129833dcfbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vat_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###
