"""add multi-tenancy: users, companies, company_id scoping

Revision ID: d3708a703dac
Revises: 7d1b1420b942
Create Date: 2026-08-02 11:05:01.558181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3708a703dac'
down_revision: Union[str, Sequence[str], None] = '7d1b1420b942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to preserve data via rename ###
    op.rename_table('company_settings', 'companies')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('counterparties') as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_counterparties_company_id', 'companies', ['company_id'], ['id']
        )
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(
            'uq_invoice_company_number', ['company_id', 'invoice_number']
        )
        batch_op.create_foreign_key(
            'fk_invoices_company_id', 'companies', ['company_id'], ['id']
        )
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_products_company_id', 'companies', ['company_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_constraint('fk_products_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.drop_constraint('fk_invoices_company_id', type_='foreignkey')
        batch_op.drop_constraint('uq_invoice_company_number', type_='unique')
        batch_op.drop_column('company_id')
    with op.batch_alter_table('counterparties') as batch_op:
        batch_op.drop_constraint('fk_counterparties_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')
    op.drop_table('users')
    op.rename_table('companies', 'company_settings')
    # ### end Alembic commands ###
